version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin 124677911839.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building WAR using Maven...
      - mvn clean package
      - echo Building the Docker image...
      - docker build -t my-project .

  post_build:
    commands:
      - echo Tagging image...
      - docker tag my-project:latest 124677911839.dkr.ecr.ap-south-1.amazonaws.com/my-project:latest
      - echo Pushing image to ECR...
      - docker push 124677911839.dkr.ecr.ap-south-1.amazonaws.com/my-project:latest
      - echo Writing image definitions file...
      - printf '[{"name":"my-project","imageUri":"124677911839.dkr.ecr.ap-south-1.amazonaws.com/my-project:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
