apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebcalculator-deployment
  labels:
    app: javawebcalculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebcalculator
  template:
    metadata:
      labels:
        app: javawebcalculator
    spec:
      containers:
      - name: javawebcalculator
        image: fareed1/new
        ports:
        - containerPort: 8080
